'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

type Tab = 'obsah' | 'tym' | 'projekty' | 'zpravy' | 'odbery' | 'analytika' | 'verze';
const input = 'w-full px-3 py-2.5 rounded-lg bg-[#0a1020] border border-white/10 text-white text-sm focus:outline-none focus:border-[#c9a84c] placeholder:text-white/25';
const card = 'bg-[rgba(14,24,43,.92)] border border-white/10 rounded-2xl p-5 md:p-6';
const primary = 'bg-[#c9a84c] text-[#0a1628] px-5 py-2.5 rounded-lg text-sm font-bold hover:bg-[#dfc06a] disabled:opacity-50';
const ghost = 'border border-white/15 text-white/70 px-4 py-2 rounded-lg text-sm hover:border-[#c9a84c] hover:text-[#c9a84c]';
const label = 'block text-white/45 text-[11px] font-semibold uppercase tracking-wider mb-1.5';

function Field({ label: title, value, onChange, textarea = false, type = 'text', placeholder = '' }: any) {
  return <label className="block"><span className={label}>{title}</span>{textarea ? <textarea rows={4} className={input} value={value || ''} placeholder={placeholder} onChange={(e) => onChange(e.target.value)}/> : <input type={type} className={input} value={value ?? ''} placeholder={placeholder} onChange={(e) => onChange(e.target.value)}/>}</label>;
}

async function optimizeImage(file: File) {
  if (file.type === 'image/svg+xml' || file.type === 'image/gif') return file;
  const bitmap = await createImageBitmap(file);
  const scale = Math.min(1, 2000 / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement('canvas');
  canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale);
  canvas.getContext('2d')!.drawImage(bitmap, 0, 0, canvas.width, canvas.height);
  const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((b) => b ? resolve(b) : reject(new Error('Optimalizace selhala')), 'image/webp', .84));
  return new File([blob], file.name.replace(/\.[^.]+$/, '') + '.webp', { type: 'image/webp' });
}

function Upload({ token, directory, onUploaded }: { token: string; directory: string; onUploaded: (path: string) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <label className={`${ghost} cursor-pointer inline-block`}>{busy ? 'Optimalizuji a nahrávám…' : '+ Nahrát fotografie'}<input hidden multiple type="file" accept="image/*" disabled={busy} onChange={async (e) => {
    const files = Array.from(e.target.files || []); e.target.value = ''; setBusy(true); setError('');
    try { for (const original of files) { const file = await optimizeImage(original); const data = new FormData(); data.append('file', file); data.append('directory', directory); const res = await fetch('/api/upload', { method: 'POST', headers: { authorization: `Bearer ${token}` }, body: data }); const json = await res.json(); if (!res.ok) throw new Error(json.error); onUploaded(json.path); } } catch (err) { setError(err instanceof Error ? err.message : 'Upload selhal'); } finally { setBusy(false); }
  }}/>{error && <span className="block text-red-400 text-xs mt-1">{error}</span>}</label>;
}

const slugify = (v: string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export default function Admin() {
  const router = useRouter(); const importRef = useRef<HTMLInputElement>(null);
  const [token, setToken] = useState(''); const [loading, setLoading] = useState(true); const [tab, setTab] = useState<Tab>('obsah');
  const [content, setContent] = useState<any>(); const [messages, setMessages] = useState<any[]>([]); const [subscribers, setSubscribers] = useState<any[]>([]); const [analytics, setAnalytics] = useState<any>(); const [versions, setVersions] = useState<any[]>([]);
  const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [search, setSearch] = useState(''); const [messageFilter, setMessageFilter] = useState('all');
  const auth = useCallback((extra: HeadersInit = {}) => ({ ...extra, authorization: `Bearer ${localStorage.getItem('dd_admin_session') || ''}` }), []);

  const reloadMeta = useCallback(async () => {
    const [m, s, a, v] = await Promise.all(['/api/contact-messages', '/api/watch-subscribers', '/api/analytics', '/api/versions'].map((url) => fetch(url, { headers: auth() }).then((r) => r.ok ? r.json() : [])));
    setMessages(Array.isArray(m) ? m : []); setSubscribers(Array.isArray(s) ? s : []); setAnalytics(a); setVersions(Array.isArray(v) ? v : []);
  }, [auth]);

  useEffect(() => { const stored = localStorage.getItem('dd_admin_session'); if (!stored) { router.replace('/admin/login'); return; } setToken(stored);
    fetch('/api/setup-features', { method: 'POST', headers: { authorization: `Bearer ${stored}` } })
      .then(() => Promise.all([fetch('/api/draft', { headers: { authorization: `Bearer ${stored}` }, cache: 'no-store' }).then((r) => { if (r.status === 401) throw new Error('auth'); return r.json(); }), reloadMeta()]))
      .then(([draft]) => setContent(draft)).catch(() => { localStorage.removeItem('dd_admin_session'); router.replace('/admin/login'); }).finally(() => setLoading(false));
  }, [reloadMeta, router]);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault(); }; addEventListener('beforeunload', warn); return () => removeEventListener('beforeunload', warn); }, [dirty]);

  const update = (path: (string | number)[], value: any) => { setContent((old: any) => { const next = structuredClone(old); let node = next; path.slice(0, -1).forEach((key) => node = node[key]); node[path.at(-1)!] = value; return next; }); setDirty(true); setNotice(''); };
  const updateItem = (key: string, i: number, values: any) => { const list = [...content[key]]; list[i] = { ...list[i], ...values }; update([key], list); };
  const saveDraft = async () => { setBusy(true); const res = await fetch('/api/draft', { method: 'PUT', headers: auth({ 'content-type': 'application/json' }), body: JSON.stringify(content) }); setBusy(false); if (res.ok) { setDirty(false); setNotice('Koncept uložen. Veřejný web se nezměnil.'); } else setNotice('Uložení konceptu selhalo.'); };
  const publish = async () => { if (!confirm('Opravdu publikovat koncept na veřejný web?')) return; setBusy(true); await saveDraft(); const res = await fetch('/api/publish', { method: 'POST', headers: auth({ 'content-type': 'application/json' }), body: JSON.stringify({ content }) }); const data = await res.json(); setBusy(false); if (res.ok) { setDirty(false); setNotice(`Publikováno. E-mailových upozornění ve frontě: ${data.notification?.queued || 0}.`); reloadMeta(); } else setNotice(data.error || 'Publikování selhalo.'); };
  const download = () => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' })); a.download = `ddhomeinvest-zaloha-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(a.href); };

  const filteredMessages = useMemo(() => messages.filter((m) => (messageFilter === 'all' || m.status === messageFilter) && `${m.name} ${m.email} ${m.phone} ${m.message}`.toLowerCase().includes(search.toLowerCase())), [messages, messageFilter, search]);
  const patchMessage = async (id: number, values: any) => { const old = messages.find((m) => m.id === id); setMessages((all) => all.map((m) => m.id === id ? { ...m, ...values } : m)); await fetch(`/api/contact-messages/${id}`, { method: 'PATCH', headers: auth({ 'content-type': 'application/json' }), body: JSON.stringify({ status: values.status ?? old.status, admin_note: values.admin_note ?? old.admin_note }) }); };
  const csv = () => { const rows = [['datum','jmeno','email','telefon','stav','zprava'], ...filteredMessages.map((m) => [m.created_at,m.name,m.email,m.phone,m.status,m.message])]; const esc = (x: any) => `"${String(x || '').replace(/"/g,'""')}"`; const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\ufeff' + rows.map((r) => r.map(esc).join(';')).join('\n')], { type: 'text/csv' })); a.download = 'poptavky.csv'; a.click(); };

  if (loading || !content) return <div className="min-h-screen bg-[#0a1020] text-white flex items-center justify-center">Načítám administraci…</div>;
  const nav: [Tab,string][] = [['obsah','Obsah'],['tym','Tým'],['projekty','Projekty'],['zpravy',`Poptávky (${messages.filter(m=>m.status==='new').length})`],['odbery','Hlídací pes'],['analytika','Analytika'],['verze','Verze a zálohy']];

  const projectEditor = (key: 'currentProjects'|'soldProjects') => <section className="space-y-4"><div className="flex justify-between items-center"><h2 className="font-heading text-xl font-bold">{key === 'currentProjects' ? 'Aktuální projekty' : 'Historie prodejů'}</h2><button className={ghost} onClick={() => update([key], [...content[key], { id: Date.now(), title: 'Nový projekt', slug: '', location: '', address: '', latitude: '', longitude: '', description: '', descriptionLong: '', status: key === 'currentProjects' ? 'Připravujeme' : 'Prodáno', price: '', area: '', disposition: '', floor: '', ownership: 'Osobní', penb: '', completionDate: '', images: [], imageCaptions: {}, features: [], timeline: [] }])}>+ Přidat</button></div>
    {content[key].map((p: any, i: number) => <article className={card} key={p.id}><div className="flex justify-between gap-4 mb-5"><div><h3 className="font-bold">{p.title}</h3><a target="_blank" href={`/projekty/${p.slug || slugify(p.title)}/`} className="text-[#c9a84c] text-xs">Otevřít detail ↗</a></div><button className="text-red-400 text-xs" onClick={() => { if(confirm('Smazat projekt?')) update([key], content[key].filter((_:any,n:number)=>n!==i)); }}>Smazat</button></div>
      <div className="grid md:grid-cols-3 gap-4"><Field label="Název" value={p.title} onChange={(v:string)=>updateItem(key,i,{title:v,slug:p.slug || slugify(v)})}/><Field label="URL slug" value={p.slug} onChange={(v:string)=>updateItem(key,i,{slug:slugify(v)})}/><Field label="Stav" value={p.status} onChange={(v:string)=>updateItem(key,i,{status:v})}/><Field label="Lokalita" value={p.location} onChange={(v:string)=>updateItem(key,i,{location:v})}/><Field label="Přesnější adresa" value={p.address} onChange={(v:string)=>updateItem(key,i,{address:v})}/><Field label="Cena" value={p.price} onChange={(v:string)=>updateItem(key,i,{price:v})}/><Field label="Zeměpisná šířka" type="number" value={p.latitude} onChange={(v:string)=>updateItem(key,i,{latitude:Number(v)})}/><Field label="Zeměpisná délka" type="number" value={p.longitude} onChange={(v:string)=>updateItem(key,i,{longitude:Number(v)})}/><Field label="Dispozice" value={p.disposition} onChange={(v:string)=>updateItem(key,i,{disposition:v})}/><Field label="Plocha" value={p.area} onChange={(v:string)=>updateItem(key,i,{area:v})}/><Field label="Podlaží" value={p.floor} onChange={(v:string)=>updateItem(key,i,{floor:v})}/><Field label="Vlastnictví" value={p.ownership} onChange={(v:string)=>updateItem(key,i,{ownership:v})}/><Field label="PENB" value={p.penb} onChange={(v:string)=>updateItem(key,i,{penb:v})}/><Field label="Předpokládané dokončení" value={p.completionDate} onChange={(v:string)=>updateItem(key,i,{completionDate:v})}/></div>
      <div className="grid md:grid-cols-2 gap-4 mt-4"><Field label="Krátký popis" textarea value={p.description} onChange={(v:string)=>updateItem(key,i,{description:v})}/><Field label="Text detailu" textarea value={p.descriptionLong} onChange={(v:string)=>updateItem(key,i,{descriptionLong:v})}/><Field label="Přednosti (jedna na řádek)" textarea value={(p.features||[]).join('\n')} onChange={(v:string)=>updateItem(key,i,{features:v.split('\n').filter(Boolean)})}/><Field label="Tagy (oddělené čárkou)" textarea value={(p.tags||[]).join(', ')} onChange={(v:string)=>updateItem(key,i,{tags:v.split(',').map(x=>x.trim()).filter(Boolean)})}/></div>
      <div className="mt-6"><span className={label}>Fotografie hotového bytu – první je úvodní, pořadí změňte přetažením</span><div className="flex flex-wrap gap-3 mb-3">{(p.images||[]).map((src:string,n:number)=><div draggable onDragStart={(e)=>e.dataTransfer.setData('text/plain',String(n))} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));const imgs=[...p.images];const [item]=imgs.splice(from,1);imgs.splice(n,0,item);updateItem(key,i,{images:imgs});}} key={src} className="w-36"><img src={src} alt="" className="w-36 h-24 object-cover rounded-lg border border-white/10"/><input aria-label="Popisek fotografie" className={`${input} mt-1 !py-1 text-xs`} placeholder="Popisek" value={p.imageCaptions?.[src]||''} onChange={(e)=>updateItem(key,i,{imageCaptions:{...p.imageCaptions,[src]:e.target.value}})}/><button className="text-red-400 text-xs mt-1" onClick={()=>updateItem(key,i,{images:p.images.filter((x:string)=>x!==src)})}>Odstranit</button></div>)}</div><Upload token={token} directory={`projects/${p.slug || p.id}`} onUploaded={(src)=>updateItem(key,i,{images:[...(p.images||[]),src]})}/></div>
      {key === 'currentProjects' && <div className="mt-6"><div className="flex justify-between"><span className={label}>Průběh rekonstrukce (bez fotografií)</span><button className="text-[#c9a84c] text-xs" onClick={()=>updateItem(key,i,{timeline:[...(p.timeline||[]),{title:'Nová fáze',description:'',status:'upcoming'}]})}>+ Fáze</button></div><div className="space-y-3">{(p.timeline||[]).map((step:any,n:number)=><div className="grid md:grid-cols-[1fr_2fr_160px_auto] gap-2" key={n}><input className={input} value={step.title} onChange={(e)=>{const x=[...p.timeline];x[n]={...step,title:e.target.value};updateItem(key,i,{timeline:x});}}/><input className={input} value={step.description} onChange={(e)=>{const x=[...p.timeline];x[n]={...step,description:e.target.value};updateItem(key,i,{timeline:x});}}/><select className={input} value={step.status} onChange={(e)=>{const x=[...p.timeline];x[n]={...step,status:e.target.value};updateItem(key,i,{timeline:x});}}><option value="done">Hotovo</option><option value="current">Právě probíhá</option><option value="upcoming">Čeká</option></select><button className="text-red-400" onClick={()=>updateItem(key,i,{timeline:p.timeline.filter((_:any,j:number)=>j!==n)})}>×</button></div>)}</div></div>}
      <button className={`${ghost} mt-6`} onClick={()=>{const to=key==='currentProjects'?'soldProjects':'currentProjects';update([key],content[key].filter((_:any,n:number)=>n!==i));setContent((old:any)=>({...old,[to]:[...old[to],{...p,status:to==='soldProjects'?'Prodáno':p.status}]}));}}>Přesunout do {key==='currentProjects'?'historie':'aktuálních'}</button>
    </article>)}</section>;

  return <div className="min-h-screen bg-[#0a1020] text-white"><header className="sticky top-0 z-40 bg-[#0a1020]/95 backdrop-blur border-b border-white/10"><div className="max-w-7xl mx-auto px-4 py-3 flex flex-wrap gap-3 justify-between items-center"><div><b>D&D Administrace</b><p className="text-white/35 text-xs">{dirty ? 'Neuložené změny' : 'Koncept uložen'}</p></div><div className="flex gap-2"><button className={ghost} onClick={saveDraft} disabled={busy}>Uložit koncept</button><a className={ghost} href="/?preview=1" target="_blank">Náhled</a><button className={primary} onClick={publish} disabled={busy}>Publikovat</button><button className={ghost} onClick={()=>{localStorage.removeItem('dd_admin_session');router.replace('/admin/login');}}>Odhlásit</button></div></div><nav className="max-w-7xl mx-auto px-4 flex overflow-x-auto">{nav.map(([id,text])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-3 whitespace-nowrap text-sm border-b-2 ${tab===id?'border-[#c9a84c] text-[#c9a84c]':'border-transparent text-white/45'}`}>{text}</button>)}</nav></header>
    <main className="max-w-7xl mx-auto p-4 md:p-7 space-y-7">{notice && <div className="bg-[#c9a84c]/10 border border-[#c9a84c]/30 rounded-xl p-4 text-sm text-[#dfc06a]">{notice}</div>}
      {tab==='obsah' && <><section className={card}><h2 className="font-heading text-xl font-bold mb-5">Úvod</h2><div className="grid md:grid-cols-2 gap-4"><Field label="Titulek" value={content.heroContent.title} onChange={(v:string)=>update(['heroContent','title'],v)}/><Field label="Podtitulek" value={content.heroContent.subtitle} onChange={(v:string)=>update(['heroContent','subtitle'],v)}/><Field label="Popis" textarea value={content.heroContent.description} onChange={(v:string)=>update(['heroContent','description'],v)}/></div></section><section className={card}><h2 className="font-heading text-xl font-bold mb-5">O nás a filozofie</h2><div className="space-y-4"><Field label="Nadpis O nás" value={content.aboutContent.sectionTitle} onChange={(v:string)=>update(['aboutContent','sectionTitle'],v)}/><Field label="Úvod O nás" textarea value={content.aboutContent.intro} onChange={(v:string)=>update(['aboutContent','intro'],v)}/><Field label="Filozofie – odstavce po řádcích" textarea value={content.philosophyContent.paragraphs.join('\n')} onChange={(v:string)=>update(['philosophyContent','paragraphs'],v.split('\n').filter(Boolean))}/></div></section><section className={card}><h2 className="font-heading text-xl font-bold mb-5">Kontakt</h2><div className="grid md:grid-cols-2 gap-4"><Field label="Telefon" value={content.siteConfig.phone} onChange={(v:string)=>update(['siteConfig','phone'],v)}/><Field label="E-mail" value={content.siteConfig.email} onChange={(v:string)=>update(['siteConfig','email'],v)}/><Field label="Adresa" value={content.siteConfig.address} onChange={(v:string)=>update(['siteConfig','address'],v)}/><Field label="Nadpis" value={content.contactContent.sectionSubtitle} onChange={(v:string)=>update(['contactContent','sectionSubtitle'],v)}/></div></section></>}
      {tab==='tym' && <div className="space-y-4">{content.teamMembers.map((m:any,i:number)=><section className={card} key={i}><div className="grid md:grid-cols-[140px_1fr] gap-5"><div><img src={m.image} alt="" className="w-32 h-40 object-cover rounded-xl mb-2"/><Upload token={token} directory="team" onUploaded={(src)=>updateItem('teamMembers',i,{image:src})}/></div><div className="grid md:grid-cols-2 gap-4"><Field label="Jméno" value={m.name} onChange={(v:string)=>updateItem('teamMembers',i,{name:v})}/><Field label="Role" value={m.role} onChange={(v:string)=>updateItem('teamMembers',i,{role:v})}/><Field label="E-mail" value={m.email} onChange={(v:string)=>updateItem('teamMembers',i,{email:v})}/><Field label="Podtitulek" value={m.subtitle} onChange={(v:string)=>updateItem('teamMembers',i,{subtitle:v})}/><div className="md:col-span-2"><Field label="Popis" textarea value={m.description} onChange={(v:string)=>updateItem('teamMembers',i,{description:v})}/></div></div></div></section>)}</div>}
      {tab==='projekty' && <div className="space-y-12">{projectEditor('currentProjects')}{projectEditor('soldProjects')}</div>}
      {tab==='zpravy' && <><div className={`${card} flex flex-wrap gap-3`}><input className={`${input} max-w-sm`} placeholder="Hledat…" value={search} onChange={e=>setSearch(e.target.value)}/><select className={`${input} max-w-48`} value={messageFilter} onChange={e=>setMessageFilter(e.target.value)}><option value="all">Všechny stavy</option><option value="new">Nové</option><option value="contacted">Kontaktované</option><option value="resolved">Vyřešené</option></select><button className={ghost} onClick={csv}>Export CSV</button></div><div className="space-y-3">{filteredMessages.map(m=><article className={card} key={m.id}><div className="flex flex-wrap justify-between gap-3"><div><b>{m.name}</b><p className="text-[#c9a84c] text-sm"><a href={`mailto:${m.email}`}>{m.email}</a> · {m.phone}</p></div><select className={`${input} max-w-44`} value={m.status||'new'} onChange={e=>patchMessage(m.id,{status:e.target.value})}><option value="new">Nová</option><option value="contacted">Kontaktována</option><option value="resolved">Vyřešena</option></select></div><p className="text-white/65 my-4 whitespace-pre-wrap">{m.message}</p><Field label="Interní poznámka" textarea value={m.admin_note} onChange={(v:string)=>setMessages(all=>all.map(x=>x.id===m.id?{...x,admin_note:v}:x))}/><button className={`${ghost} mt-2`} onClick={()=>patchMessage(m.id,{admin_note:m.admin_note})}>Uložit poznámku</button></article>)}</div></>}
      {tab==='odbery' && <section className={card}><h2 className="font-heading text-xl font-bold mb-2">Hlídací pes</h2><p className="text-white/45 text-sm mb-5">Aktivní: {subscribers.filter(s=>s.confirmed&&!s.unsubscribed_at).length} · Čeká na potvrzení: {subscribers.filter(s=>!s.confirmed&&!s.unsubscribed_at).length}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-white/35 text-left"><tr><th className="py-2">E-mail</th><th>Stav</th><th>Datum</th></tr></thead><tbody>{subscribers.map(s=><tr className="border-t border-white/10" key={s.id}><td className="py-3">{s.email}</td><td>{s.unsubscribed_at?'Odhlášen':s.confirmed?'Aktivní':'Nepotvrzen'}</td><td className="text-white/40">{s.created_at}</td></tr>)}</tbody></table></div></section>}
      {tab==='analytika' && <><section className={card}><h2 className="font-heading text-xl font-bold mb-5">Posledních 30 dní</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{(analytics?.events||[]).map((x:any)=><div className="bg-white/5 rounded-xl p-4" key={x.event}><p className="text-white/40 text-xs uppercase">{x.event}</p><b className="text-3xl text-[#c9a84c]">{x.count}</b></div>)}</div></section><section className={card}><h2 className="font-bold mb-4">Nejprohlíženější projekty</h2>{(analytics?.projects||[]).map((x:any)=><p key={x.project_id} className="border-t border-white/10 py-2">Projekt ID {x.project_id}: <b>{x.count}</b></p>)}</section></>}
      {tab==='verze' && <><section className={`${card} flex flex-wrap gap-3`}><button className={ghost} onClick={download}>Exportovat JSON zálohu</button><button className={ghost} onClick={()=>importRef.current?.click()}>Importovat JSON</button><input ref={importRef} hidden type="file" accept="application/json" onChange={async e=>{try{const json=JSON.parse(await e.target.files![0].text());setContent(json);setDirty(true);setNotice('Záloha načtena jako koncept. Zkontrolujte ji a uložte.');}catch{setNotice('Neplatná záloha.');}}}/></section><section className={card}><h2 className="font-heading text-xl font-bold mb-4">Historie publikování</h2>{versions.map(v=><div className="flex justify-between items-center border-t border-white/10 py-3" key={v.id}><div><b>Verze #{v.id}</b><p className="text-white/35 text-xs">{v.created_at} · {v.created_by}</p></div><button className={ghost} onClick={async()=>{if(!confirm('Načíst tuto verzi jako koncept?'))return;const r=await fetch(`/api/versions/${v.id}`,{headers:auth()});setContent(await r.json());setDirty(true);setNotice('Historická verze načtena jako koncept.');}}>Obnovit do konceptu</button></div>)}</section></>}
    </main></div>;
}
